[project]
name = "house"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "google-genai>=1.61.0",
    "uvicorn[standard]>=0.40.0",
]
